// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::subsystem1topLeft;
std::shared_ptr<frc::SpeedController> RobotMap::subsystem1topRight;
std::shared_ptr<frc::SpeedController> RobotMap::subsystem1bottomLeft;
std::shared_ptr<frc::SpeedController> RobotMap::subsystem1bottomRight;
std::shared_ptr<frc::MecanumDrive> RobotMap::subsystem1MecanumDrive1;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    subsystem1topLeft.reset(new frc::VictorSP(0));
    lw->AddActuator("Subsystem1", "topLeft", std::static_pointer_cast<frc::VictorSP>(subsystem1topLeft));
    
    subsystem1topRight.reset(new frc::VictorSP(1));
    lw->AddActuator("Subsystem1", "topRight", std::static_pointer_cast<frc::VictorSP>(subsystem1topRight));
    
    subsystem1bottomLeft.reset(new frc::VictorSP(2));
    lw->AddActuator("Subsystem1", "bottomLeft", std::static_pointer_cast<frc::VictorSP>(subsystem1bottomLeft));
    
    subsystem1bottomRight.reset(new frc::Spark(3));
    lw->AddActuator("Subsystem1", "bottomRight", std::static_pointer_cast<frc::Spark>(subsystem1bottomRight));
    
    subsystem1MecanumDrive1.reset(new frc::MecanumDrive(*subsystem1topLeft, *subsystem1topRight,
              *subsystem1bottomRight, *subsystem1bottomLeft));
    lw->AddActuator("Subsystem1", "Mecanum Drive 1", subsystem1MecanumDrive1);
    subsystem1MecanumDrive1->SetSafetyEnabled(true);
        subsystem1MecanumDrive1->SetExpiration(0.1);
        subsystem1MecanumDrive1->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
